### ISSUE TITLE
Getting an error when trying to use usePermissions

### ISSUE THREAD

**Issue by julienV** [marmelab/ra-auth-cognito#7]
Hi,
I am getting an error when trying to use userPermissions:

`No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (http://localhost:3000/static/js/bundle.js:139478:11)
    at useBaseQuery (http://localhost:3000/static/js/bundle.js:139706:89)
    at useQuery (http://localhost:3000/static/js/bundle.js:140078:69)
    at usePermissions (http://localhost:3000/static/js/bundle.js:79437:69)
    at App (http://localhost:3000/main.d68b18a03d9add2c7b72.hot-update.js:111:62)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:124018:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:127304:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:128600:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:113610:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:113654:20)`

react admin 4.9.1
ra auth cognito 1.0.1

**Comment by julienV** [comment]
my bad, it works as expected...
